# Server
spring.application.name=openshelf
server.port=9000

## Data JPA
spring.datasource.url=jdbc:postgresql://localhost:5432/openshelf
spring.jpa.hibernate.ddl-auto=update
spring.datasource.password=postgres
spring.datasource.username=postgres
spring.jpa.show-sql=true
